name: Build Clojure MSI
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package MSI
        shell: pwsh
        run: .\build-clojure-msi.ps1
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest-installer
          path: *.msi
